apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: tester
          mountPath: /app/data
        env:
        - name: MYSQL_DATABASE
          value: bit-blog

        - name: MYSQL_ROOT_PASSWORD
          value: password
        
        - name: MYSQL_ROOT_USER
          value: root
      volumes:
      - name: tester
        persistentVolumeClaim:
         claimName: mypvc



---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3300
    targetPort: 3306

